### ISSUE TITLE
TypeError: Error while loading rule 'eslint-comments/no-unused-disable': Cannot read property 'report' of undefined

### ISSUE THREAD

**Issue by 9renpoto** [mysticatea/eslint-plugin-eslint-comments#4]
Connect to https://github.com/userdive/agent.js/pull/122

https://travis-ci.org/userdive/agent.js/jobs/264210941#L462

```
Started a new flow server: \Error while loading rule 'eslint-comments/no-unused-disable': Cannot read property 'report' of undefined

TypeError: Error while loading rule 'eslint-comments/no-unused-disable': Cannot read property 'report' of undefined
    at Object.create (/home/travis/build/[secure]/agent.js/node_modules/eslint-plugin-eslint-comments/lib/rules/no-unused-disable.js:31:46)
    at Object.keys.filter.forEach.key (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/linter.js:874:67)
    at Array.forEach (<anonymous>)
    at Linter.verify (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/linter.js:847:93)
    at processText (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/cli-engine.js:203:31)
    at processFile (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/cli-engine.js:245:18)
    at executeOnFile (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/cli-engine.js:585:25)
    at fileList.forEach.fileInfo (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/cli-engine.js:622:13)
    at Array.forEach (<anonymous>)
    at CLIEngine.executeOnFiles (/home/travis/build/[secure]/agent.js/node_modules/eslint/lib/cli-engine.js:621:18)
```

Please help.

**Comment by mysticatea** [comment]
Thank you for this issue.

Could you ensure to use the latest version of `eslint-plugin-eslint-comments`?
That bug should be fixed in [v1.0.3](https://github.com/mysticatea/eslint-plugin-eslint-comments/releases/tag/v1.0.3).

**Comment by mysticatea** [comment]
I confirmed that it uses an older version. Please use the latest version.

**Comment by 9renpoto** [comment]
I'm sorry, I will check it!
Thank you.
